/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TrainingSessionsCreateImport } from './routes/training-sessions/create'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TrainingSessionsCreateRoute = TrainingSessionsCreateImport.update({
  id: '/training-sessions/create',
  path: '/training-sessions/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/training-sessions/create': {
      id: '/training-sessions/create'
      path: '/training-sessions/create'
      fullPath: '/training-sessions/create'
      preLoaderRoute: typeof TrainingSessionsCreateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/training-sessions/create': typeof TrainingSessionsCreateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/training-sessions/create': typeof TrainingSessionsCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/training-sessions/create': typeof TrainingSessionsCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/training-sessions/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/training-sessions/create'
  id: '__root__' | '/' | '/training-sessions/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrainingSessionsCreateRoute: typeof TrainingSessionsCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrainingSessionsCreateRoute: TrainingSessionsCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/training-sessions/create"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/training-sessions/create": {
      "filePath": "training-sessions/create.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
