/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedPracticeSessionsIndexImport } from './routes/_authenticated/practice-sessions/index'
import { Route as AuthenticatedPracticeSessionsCreateImport } from './routes/_authenticated/practice-sessions/create'
import { Route as AuthenticatedPracticeSessionsIdIndexImport } from './routes/_authenticated/practice-sessions/$id/index'
import { Route as AuthenticatedPracticeSessionsIdPlayImport } from './routes/_authenticated/practice-sessions/$id/play'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedPracticeSessionsIndexRoute =
  AuthenticatedPracticeSessionsIndexImport.update({
    id: '/practice-sessions/',
    path: '/practice-sessions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPracticeSessionsCreateRoute =
  AuthenticatedPracticeSessionsCreateImport.update({
    id: '/practice-sessions/create',
    path: '/practice-sessions/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPracticeSessionsIdIndexRoute =
  AuthenticatedPracticeSessionsIdIndexImport.update({
    id: '/practice-sessions/$id/',
    path: '/practice-sessions/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPracticeSessionsIdPlayRoute =
  AuthenticatedPracticeSessionsIdPlayImport.update({
    id: '/practice-sessions/$id/play',
    path: '/practice-sessions/$id/play',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/practice-sessions/create': {
      id: '/_authenticated/practice-sessions/create'
      path: '/practice-sessions/create'
      fullPath: '/practice-sessions/create'
      preLoaderRoute: typeof AuthenticatedPracticeSessionsCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/practice-sessions/': {
      id: '/_authenticated/practice-sessions/'
      path: '/practice-sessions'
      fullPath: '/practice-sessions'
      preLoaderRoute: typeof AuthenticatedPracticeSessionsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/practice-sessions/$id/play': {
      id: '/_authenticated/practice-sessions/$id/play'
      path: '/practice-sessions/$id/play'
      fullPath: '/practice-sessions/$id/play'
      preLoaderRoute: typeof AuthenticatedPracticeSessionsIdPlayImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/practice-sessions/$id/': {
      id: '/_authenticated/practice-sessions/$id/'
      path: '/practice-sessions/$id'
      fullPath: '/practice-sessions/$id'
      preLoaderRoute: typeof AuthenticatedPracticeSessionsIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedPracticeSessionsCreateRoute: typeof AuthenticatedPracticeSessionsCreateRoute
  AuthenticatedPracticeSessionsIndexRoute: typeof AuthenticatedPracticeSessionsIndexRoute
  AuthenticatedPracticeSessionsIdPlayRoute: typeof AuthenticatedPracticeSessionsIdPlayRoute
  AuthenticatedPracticeSessionsIdIndexRoute: typeof AuthenticatedPracticeSessionsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPracticeSessionsCreateRoute:
    AuthenticatedPracticeSessionsCreateRoute,
  AuthenticatedPracticeSessionsIndexRoute:
    AuthenticatedPracticeSessionsIndexRoute,
  AuthenticatedPracticeSessionsIdPlayRoute:
    AuthenticatedPracticeSessionsIdPlayRoute,
  AuthenticatedPracticeSessionsIdIndexRoute:
    AuthenticatedPracticeSessionsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/practice-sessions/create': typeof AuthenticatedPracticeSessionsCreateRoute
  '/practice-sessions': typeof AuthenticatedPracticeSessionsIndexRoute
  '/practice-sessions/$id/play': typeof AuthenticatedPracticeSessionsIdPlayRoute
  '/practice-sessions/$id': typeof AuthenticatedPracticeSessionsIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/practice-sessions/create': typeof AuthenticatedPracticeSessionsCreateRoute
  '/practice-sessions': typeof AuthenticatedPracticeSessionsIndexRoute
  '/practice-sessions/$id/play': typeof AuthenticatedPracticeSessionsIdPlayRoute
  '/practice-sessions/$id': typeof AuthenticatedPracticeSessionsIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/practice-sessions/create': typeof AuthenticatedPracticeSessionsCreateRoute
  '/_authenticated/practice-sessions/': typeof AuthenticatedPracticeSessionsIndexRoute
  '/_authenticated/practice-sessions/$id/play': typeof AuthenticatedPracticeSessionsIdPlayRoute
  '/_authenticated/practice-sessions/$id/': typeof AuthenticatedPracticeSessionsIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/sign-in'
    | '/practice-sessions/create'
    | '/practice-sessions'
    | '/practice-sessions/$id/play'
    | '/practice-sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/sign-in'
    | '/practice-sessions/create'
    | '/practice-sessions'
    | '/practice-sessions/$id/play'
    | '/practice-sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/practice-sessions/create'
    | '/_authenticated/practice-sessions/'
    | '/_authenticated/practice-sessions/$id/play'
    | '/_authenticated/practice-sessions/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/practice-sessions/create",
        "/_authenticated/practice-sessions/",
        "/_authenticated/practice-sessions/$id/play",
        "/_authenticated/practice-sessions/$id/"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/_authenticated/practice-sessions/create": {
      "filePath": "_authenticated/practice-sessions/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/practice-sessions/": {
      "filePath": "_authenticated/practice-sessions/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/practice-sessions/$id/play": {
      "filePath": "_authenticated/practice-sessions/$id/play.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/practice-sessions/$id/": {
      "filePath": "_authenticated/practice-sessions/$id/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
